app/views/forms.py
from flask import Blueprint, render_template, url_for, request, flash, redirect
from flask_login import login_required, current_user
from flask_wtf import FlaskForm
from wtforms import SelectField, StringField, SubmitField
from wtforms.validators import InputRequired, Length
from app.models import Incident, User, Incident_History
from app.extensions import db
from datetime import datetime

#creating blueprint
blueprint = Blueprint("forms", __name__)

#making a list of tags
tagNames = ['', 'Account Request', 'Equipment', 'File Issue', 'Hardware Issue', 'Information Security', 'Inventory', 'Network Issue', 'New Hire', 'Password Reset', 'PC Allocation', 'Purchase Request',
'Software Installation', 'Software Issue']

categories = ['Low', 'Medium', 'High']

statuses = ['Open', 'In Progress', 'On Hold', 'Awaiting Callback', 'Closed']

@blueprint.route('/create-incident')
def create_incident():
    users = User.query.all()
    names = []
    for user in users:
        name = str(user.fname + " " + user.lname)
        names.append(name)

    return render_template('forms/create_incident.html', categories = categories, users = names, tagNames = tagNames)

#create incident route
@login_required
@blueprint.route('/created-incident', methods = ['GET', 'POST'])
def created_incident():
    form = request.form

    users = User.query.all()
    for user in users:
        if form["poc"] == str(user.fname + " " + user.lname):
            pocID = user.id
        if form["assignee"] == str(user.fname + " " + user.lname):
            assigneeID = user.id

    newIncident = Incident(title = form["title"],
                          category = form["category"],
                          description = form["description"],
                          date_created = datetime.now().strftime('%Y-%m-%d %I:%M'),
                          date_resolved = None,
                          state = "Open",
                          tag = str(form["tag1"] + ", " + form["tag2"] + ", " + form["tag3"]),
                          case_history = str("Ticket created on " + str(datetime.now().strftime('%Y-%m-%d %I:%M'))),
                          assignee = assigneeID,
                          point_of_contact = pocID)

    db.session.add(newIncident)
    db.session.commit()

    newIncidentHistory = Incident_History(user_id = pocID, incident_id = newIncident.incidentID, incident_history = newIncident.case_history)
    db.session.add(newIncidentHistory)
    db.session.commit()

    return redirect(url_for('home.dashboard'))

#edit ticket route
@login_required
@blueprint.route('/edit/<int:ticketID>')
def edit_incident(ticketID):
    incident = Incident.query.get(ticketID)

    users = User.query.all()
    names = []

    POC = ''
    currentAssignee = ''

    for user in users:
        name = str(user.fname + " " + user.lname)
        names.append(name)
        if incident.point_of_contact == user.id:
            POC = str(user.fname + " " + user.lname)

        if incident.assignee == user.id:
            currentAssignee = str(user.fname + " " + user.lname)

    currentTags = incident.tag.split(', ')

    return render_template('forms/edit_incident.html', incident = incident, users = names, categories = categories, tagNames = tagNames, currentTags = currentTags, POC = POC, currentAssignee = currentAssignee)

#edited ticket route
@login_required
@blueprint.route('/edit/<int:ticketID>', methods=["GET", "POST"])
def edited_incident(ticketID):
    form = request.form

    incident = Incident.query.get(ticketID)

    if incident.title != form["title"] and form["title"] != '':
        incident.title = form["title"]
    if incident.category != form["category"] and form["category"] != '':
        incident.category = form["category"]
    if incident.description != form["description"] and form["description"] != '':
        incident.description = form["description"]

    assignedUser = User.query.get(incident.assignee)
    assignedUserName = str(assignedUser.fname + " " + assignedUser.lname)

    poc = User.query.get(incident.point_of_contact)
    pocName = str(poc.fname + " " + poc.lname)

    if assignedUserName != form["assignee"] and form["assignee"] != '':
        for user in User.query.all():
            if form["assignee"] == str(user.fname + " " + user.lname):
                incident.assignee = user.id

    if pocName != form["poc"] and form["poc"] != '':
        for user in User.query.all():
            if form["poc"] == str(user.fname + " " + user.lname):
                incident.point_of_contact = user.id

    individualTags = incident.tag.split(', ')
    if len(individualTags) == 1 and form["tag2"] != '':
        incident.tag = str(incident.tag + ", " + form["tag2"])
        if form["tag3"] != '':
            incident.tag = str(incident.tag + ", " + form["tag2"] + ", " + form["tag3"])

    if len(individualTags) == 2 and form["tag3"] != '':
        incident.tag = str(incident.tag + ", " + form["tag3"])

    for i in individualTags:
        if i != form["tag1"] and form["tag1"] != '':
            incident.tag.replace(i, form["tag1"])
        if i != form["tag2"] and form["tag2"] != '':
            incident.tag.replace(i, form["tag2"])
        if i != form["tag3"] and form["tag3"] != '':
            incident.tag.replace(i, form["tag3"])

    db.session.commit()
    return redirect(url_for('home.dashboard'))

#update ticket
@login_required
@blueprint.route('/update/<int:ticketID>', methods = ["GET", "POST"])
def update_incident(ticketID):
    form = request.form

    incident = Incident.query.get(ticketID)

    currentState = incident.state

    caseHistory = str("Ticket updated on " + datetime.now().strftime('%Y-%m-%d %I:%M'))

    if request.method == 'POST':
        if form["desc"] != '':
            caseHistory = str(caseHistory + "\n Message added by " + current_user.fname + " " + current_user.lname + ": " + form["desc"])
        if form["state"] != '':
            caseHistory = str(caseHistory + "\n Status updated by " + current_user.fname + " " + current_user.lname + " to: " + form["state"])
            incident.state = form["state"]
            if form["state"] == "Closed":
                incident.date_resolved = datetime.now().strftime('%Y-%m-%d %I:%M')
                caseHistory = str(caseHistory + "\n Ticket closed by " + current_user.fname + " " + current_user.lname + " on " + datetime.now().strftime('%Y-%m-%d %I:%M'))

        newIncidentHistory = Incident_History(user_id = current_user.id, incident_id = ticketID, incident_history = caseHistory)
        db.session.add(newIncidentHistory)
        db.session.commit()
        return redirect(url_for('home.dashboard'))

    return render_template('forms/update_incident.html', statuses = statuses, currentState = currentState, incident = incident)

app/views/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from app import app
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import InputRequired, Email, Length
from werkzeug.security import generate_password_hash, check_password_hash
from app.models import User
from app.extensions import db

# creating blueprint
blueprint = Blueprint("auth", __name__)

#form for logging in
class LoginForm(FlaskForm):
    username = StringField('Username', validators=[InputRequired(), Length(max=20)])
    password = PasswordField('Password', validators=[InputRequired(), Length(max=30)])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

#form for registering for an account
class RegisterForm(FlaskForm):
    email = StringField('Email', validators=[InputRequired(), Email(message='Invalid Email'), Length(max=40)])
    username = StringField('Username', validators=[InputRequired(), Length(max=20)])
    password = PasswordField('Password', validators=[InputRequired(), Length(max=30)])
    fname = StringField('First Name', validators=[InputRequired(), Length(max=20)])
    lname = StringField('Last Name', validators=[InputRequired(), Length(max=25)])
    submit = SubmitField('Register')

#form for resetting password
class PasswordResetForm(FlaskForm):
    email = StringField('Email', validators=[InputRequired()])
    old_password = PasswordField('Old Password', validators=[InputRequired()])
    new_password = PasswordField('New Password', validators=[InputRequired()])
    submit = SubmitField('Reset')

# @login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

#login route
@blueprint.route('/login', methods = ['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username = form.username.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('home.dashboard'))


    return render_template('auth/login.html', form = form)

#Register route
@blueprint.route('/register', methods = ['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='sha256')
        new_user = User(username = form.username.data, email = form.email.data, password = hashed_password, fname = form.fname.data, lname = form.lname.data, userType="User", incident_created=None, incident_assigned=None)

        db.session.add(new_user)
        db.session.commit()

    return render_template('auth/register.html', form=form)

#Password reset route
@blueprint.route('/reset-password', methods = ['GET', 'POST'])
def reset_password():
    form = PasswordResetForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user:
            if check_password_hash(user.password, form.old_password.data):
                new_pass_hashed = generate_password_hash(form.new_password.data, method='sha256')
                user.password = new_pass_hashed
                db.session.commit()

                flash('Password sucessfully reset.')
                return redirect(url_for('login'))

    return render_template('auth/reset_password.html', form=form)

#logout route
@blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

app/templates/forms/create_incident.html
{% extends 'base.html' %}
{% block head %}
{{ super() }}
	<meta charset="utf-8">
	{% block title %}<title>Create Incident</title>{% endblock title %}
{% endblock head %}

{% block body %}
{{ super() }}

<div class="limiter">
    <div class="container-login100">

    <div style="position:fixed; top:50px; left:50px;">
        <a href="{{url_for('auth.logout')}}">
            <button class="login100-form-btn" action="{{url_for('auth.logout')}}">
                Log Out
            </button>
        </a>
    </div>
    <div style="position:fixed; top:50px;">
        <a href="{{url_for('home.dashboard')}}">
            <button class="login100-form-btn" action="{{url_for('home.dashboard')}}">
                Back To Dashboard
            </button>
        </a>
    </div>

        <div class="wrap-login100 p-l-55 p-r-55 p-t-55 p-b-50">
            <form class="login100-form validate-form" action="{{url_for('forms.created_incident')}}" method="POST">
                <span class="login100-form-title p-b-33">
                    Create Incident
                </span>
               <div class="wrap-input100 validate-input"> 
                <input class="input100" type="text" name="title" placeholder="Title">
                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>
               </div>

               <div class="wrap-input100 validate-input">
                <input class="input100" list="categories" name="category" placeholder="Category">
                    <datalist id="categories">
                    {% for c in categories %}
                    <option value="{{c}}"></option>
                    {% endfor %}
                    </datalist> 
                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>
               </div>

               <div class="wrap-input100 validate-input"> 
                <input class="input100" list="tags" name="tag1" placeholder="Tag">
                    <datalist id="tags">
                    {% for t in tagNames %}
                    <option value="{{t}}"></option>
                    {% endfor %}
                    </datalist> 
                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>
               </div>

               <div class="wrap-input100 validate-input"> 
                <input class="input100" list="tags" name="tag2" placeholder="Tag">
                    <datalist id="tags">
                    {% for t in tagNames %}
                    <option value="{{t}}"></option>
                    {% endfor %}
                    </datalist> 
                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>
               </div>

               <div class="wrap-input100 validate-input"> 
                <input class="input100" list="tags" name="tag3" placeholder="Tag">
                    <datalist id="tags">
                    {% for t in tagNames %}
                    <option value="{{t}}"></option>
                    {% endfor %}
                    </datalist> 

                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>
               </div>

               <div class="wrap-input100 validate-input"> 
                <input class="input100" list="users" name="poc" placeholder="Point Of Contact">
                    <datalist id="users">
                    {% for u in users %}
                    <option value="{{u}}"></option>
                    {% endfor %}
                    </datalist> 
                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>

               <div class="wrap-input100 validate-input"> 
                <input class="input100" list="users" name="assignee" placeholder="Assigned To">
                    <datalist id="users">
                    {% for u in users %}
                    <option value="{{u}}"></option>
                    {% endfor %}
                    </datalist> 

                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>
               </div>

               <div class="wrap-input100 validate-input"> 
                <input class="input100" type="text" name="description" placeholder="Description">
                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>
               </div>

               <div class="container-login100-form-btn m-t-20">
            	<button class="login100-form-btn">
                    Create
                </button>
               </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/forms/edit_incident.html
{% extends 'base.html' %}
{% block head %}
{{ super() }}
	<meta charset="utf-8">
	{% block title %}<title>Edit Incident</title>{% endblock title %}
{% endblock head %}

{% block body %}
{{ super() }}

<div class="limiter">
    <div class="container-login100">

    <div style="position:fixed; top:50px; left:50px;">
        <a href="{{url_for('auth.logout')}}">
            <button class="login100-form-btn" action="{{url_for('auth.logout')}}">
                Log Out
            </button>
        </a>
    </div>

    <div style="position:fixed; top:50px;;">
        <a href="{{url_for('home.dashboard')}}">
            <button class="login100-form-btn" action="{{url_for('home.dashboard')}}">
                Back to Dashboard
            </button>
        </a>
    </div>

        <div class="wrap-login100 p-l-55 p-r-55 p-t-55 p-b-50">
            <form class="login100-form validate-form" action="{{url_for('forms.edited_incident', ticketID = incident.incidentID)}}" method="POST">
                <span class="login100-form-title p-b-33">
                    Edit Incident
                </span>
               <div class="wrap-input100 validate-input"> 
                <input class="input100" type="text" name="title" placeholder="{{incident.title}}">
                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>
               </div>

               <div class="wrap-input100 validate-input">
                <input class="input100" list="categories" name="category" placeholder="{{incident.category}}">
                    <datalist id="categories">
                    {% for c in categories %}
                    <option value="{{c}}"></option>
                    {% endfor %}
                    </datalist> 
                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>
               </div>

               <div class="wrap-input100 validate-input"> 
                <input class="input100" list="tags" name="tag1" placeholder="{{currentTags[0]}}">
                    <datalist id="tags">
                    {% for t in tagNames %}
                    <option value="{{t}}"></option>
                    {% endfor %}
                    </datalist> 
                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>
               </div>

               <div class="wrap-input100 validate-input"> 
                <input class="input100" list="tags" name="tag2" placeholder="{{currentTags[1]}}">
                    <datalist id="tags">
                    {% for t in tagNames %}
                    <option value="{{t}}"></option>
                    {% endfor %}
                    </datalist> 
                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>
               </div>

               <div class="wrap-input100 validate-input"> 
                <input class="input100" list="tags" name="tag3" placeholder="{{currentTags[2]}}">
                    <datalist id="tags">
                    {% for t in tagNames %}
                    <option value="{{t}}"></option>
                    {% endfor %}
                    </datalist> 

                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>
               </div>

               <div class="wrap-input100 validate-input"> 
                <input class="input100" list="users" name="poc" placeholder="Point of Contact: {{POC}}">
                    <datalist id="users">
                    {% for u in users %}
                    <option value="{{u}}"></option>
                    {% endfor %}
                    </datalist> 
                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>

               <div class="wrap-input100 validate-input"> 
                <input class="input100" list="users" name="assignee" placeholder="Current Assignee: {{currentAssignee}}">
                    <datalist id="users">
                    {% for u in users %}
                    <option value="{{u}}"></option>
                    {% endfor %}
                    </datalist> 

                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>
               </div>

               <div class="wrap-input100 validate-input"> 
                <input class="input100" type="text" name="description" placeholder="Description">
                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>
               </div>

               <div class="container-login100-form-btn m-t-20">
            	<button class="login100-form-btn">
                    Edit
                </button>
               </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/forms/update_incident.html
{% extends 'base.html' %}
{% block head %}
{{ super() }}
	<meta charset="utf-8">
	{% block title %}<title>Update Incident</title>{% endblock title %}
{% endblock head %}

{% block body %}
{{ super() }}

<div class="limiter">
    <div class="container-login100">

    <div style="position:fixed; top:50px; left:50px;">
        <a href="{{url_for('auth.logout')}}">
            <button class="login100-form-btn" action="{{url_for('auth.logout')}}">
                Log Out
            </button>
        </a>
    </div>

    <div style="position:fixed; top:50px;;">
        <a href="{{url_for('home.dashboard')}}">
            <button class="login100-form-btn" action="{{url_for('home.dashboard')}}">
                Back to Dashboard
            </button>
        </a>
    </div>

        <div class="wrap-login100 p-l-55 p-r-55 p-t-55 p-b-50">
            <form class="login100-form validate-form" action="{{url_for('forms.update_incident', ticketID = incident.incidentID)}}" method="POST">
                <span class="login100-form-title p-b-33">
                    Update Incident {{incident.title}}
                </span>
               <div class="wrap-input100 validate-input"> 
                <input class="input100" type="text" name="desc" placeholder="Message">
                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>
               </div>

               <div class="wrap-input100 validate-input">
                <input class="input100" list="statuses" name="state" placeholder="Status">
                    <datalist id="statuses">
                    {% for s in statuses %}
                    <option value="{{s}}"></option>
                    {% endfor %}
                    </datalist> 
                <span class="focus-input100-1"></span>
                <span class="focus-input100-2"></span>
               </div>

               <div class="container-login100-form-btn m-t-20">
            	<button class="login100-form-btn">
                    Update
                </button>
               </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}