app/views/forms.py
from flask import Blueprint, render_template, url_for, request, flash, redirect
from flask_login import login_required, current_user
from flask_wtf import FlaskForm
from wtforms import SelectField, StringField, SubmitField
from wtforms.validators import InputRequired, Length
from app.models import Incident, User, Incident_History
from app.extensions import db
from datetime import datetime

#creating blueprint
blueprint = Blueprint("forms", __name__)

#making a list of tags
tagNames = ['', 'Account Request', 'Equipment', 'File Issue', 'Hardware Issue', 'Information Security', 'Inventory', 'Network Issue', 'New Hire', 'Password Reset', 'PC Allocation', 'Purchase Request',
'Software Installation', 'Software Issue']

categories = ['Low', 'Medium', 'High']

statuses = ['Open', 'In Progress', 'On Hold', 'Awaiting Callback', 'Closed']

@blueprint.route('/create-incident')
def create_incident():
    users = User.query.all()
    names = []
    for user in users:
        name = str(user.fname + " " + user.lname)
        names.append(name)

    return render_template('forms/create_incident.html', categories = categories, users = names, tagNames = tagNames)

#create incident route
@login_required
@blueprint.route('/created-incident', methods = ['GET', 'POST'])
def created_incident():
    form = request.form

    users = User.query.all()
    for user in users:
        if form["poc"] == str(user.fname + " " + user.lname):
            pocID = user.id
        if form["assignee"] == str(user.fname + " " + user.lname):
            assigneeID = user.id

    newIncident = Incident(title = form["title"],
                          category = form["category"],
                          description = form["description"],
                          date_created = datetime.now().strftime('%Y-%m-%d %I:%M'),
                          date_resolved = None,
                          state = "Open",
                          tag = str(form["tag1"] + ", " + form["tag2"] + ", " + form["tag3"]),
                          case_history = str("Ticket created on " + str(datetime.now().strftime('%Y-%m-%d %I:%M'))),
                          assignee = assigneeID,
                          point_of_contact = pocID)

    db.session.add(newIncident)
    db.session.commit()

    newIncidentHistory = Incident_History(user_id = pocID, incident_id = newIncident.incidentID, incident_history = newIncident.case_history)
    db.session.add(newIncidentHistory)
    db.session.commit()

    return redirect(url_for('home.dashboard'))

#edit ticket route
@login_required
@blueprint.route('/edit/<int:ticketID>')
def edit_incident(ticketID):
    incident = Incident.query.get(ticketID)

    users = User.query.all()
    names = []

    POC = ''
    currentAssignee = ''

    for user in users:
        name = str(user.fname + " " + user.lname)
        names.append(name)
        if incident.point_of_contact == user.id:
            POC = str(user.fname + " " + user.lname)

        if incident.assignee == user.id:
            currentAssignee = str(user.fname + " " + user.lname)

    currentTags = incident.tag.split(', ')

    return render_template('forms/edit_incident.html', incident = incident, users = names, categories = categories, tagNames = tagNames, currentTags = currentTags, POC = POC, currentAssignee = currentAssignee)

#edited ticket route
@login_required
@blueprint.route('/edit/<int:ticketID>', methods=["GET", "POST"])
def edited_incident(ticketID):
    form = request.form

    incident = Incident.query.get(ticketID)

    if incident.title != form["title"] and form["title"] != '':
        incident.title = form["title"]
    if incident.category != form["category"] and form["category"] != '':
        incident.category = form["category"]
    if incident.description != form["description"] and form["description"] != '':
        incident.description = form["description"]

    assignedUser = User.query.get(incident.assignee)
    assignedUserName = str(assignedUser.fname + " " + assignedUser.lname)

    poc = User.query.get(incident.point_of_contact)
    pocName = str(poc.fname + " " + poc.lname)

    if assignedUserName != form["assignee"] and form["assignee"] != '':
        for user in User.query.all():
            if form["assignee"] == str(user.fname + " " + user.lname):
                incident.assignee = user.id

    if pocName != form["poc"] and form["poc"] != '':
        for user in User.query.all():
            if form["poc"] == str(user.fname + " " + user.lname):
                incident.point_of_contact = user.id

    individualTags = incident.tag.split(', ')
    if len(individualTags) == 1 and form["tag2"] != '':
        incident.tag = str(incident.tag + ", " + form["tag2"])
        if form["tag3"] != '':
            incident.tag = str(incident.tag + ", " + form["tag2"] + ", " + form["tag3"])

    if len(individualTags) == 2 and form["tag3"] != '':
        incident.tag = str(incident.tag + ", " + form["tag3"])

    for i in individualTags:
        if i != form["tag1"] and form["tag1"] != '':
            incident.tag.replace(i, form["tag1"])
        if i != form["tag2"] and form["tag2"] != '':
            incident.tag.replace(i, form["tag2"])
        if i != form["tag3"] and form["tag3"] != '':
            incident.tag.replace(i, form["tag3"])

    db.session.commit()
    return redirect(url_for('home.dashboard'))

#update ticket
@login_required
@blueprint.route('/update/<int:ticketID>', methods = ["GET", "POST"])
def update_incident(ticketID):
    form = request.form

    incident = Incident.query.get(ticketID)

    currentState = incident.state

    caseHistory = str("Ticket updated on " + datetime.now().strftime('%Y-%m-%d %I:%M'))

    if request.method == 'POST':
        if form["desc"] != '':
            caseHistory = str(caseHistory + "\n Message added by " + current_user.fname + " " + current_user.lname + ": " + form["desc"])
        if form["state"] != '':
            caseHistory = str(caseHistory + "\n Status updated by " + current_user.fname + " " + current_user.lname + " to: " + form["state"])
            incident.state = form["state"]
            if form["state"] == "Closed":
                incident.date_resolved = datetime.now().strftime('%Y-%m-%d %I:%M')
                caseHistory = str(caseHistory + "\n Ticket closed by " + current_user.fname + " " + current_user.lname + " on " + datetime.now().strftime('%Y-%m-%d %I:%M'))

        newIncidentHistory = Incident_History(user_id = current_user.id, incident_id = ticketID, incident_history = caseHistory)
        db.session.add(newIncidentHistory)
        db.session.commit()
        return redirect(url_for('home.dashboard'))

    return render_template('forms/update_incident.html', statuses = statuses, currentState = currentState, incident = incident)

app/views/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from app import app
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import InputRequired, Email, Length
from werkzeug.security import generate_password_hash, check_password_hash
from app.models import User
from app.extensions import db

# creating blueprint
blueprint = Blueprint("auth", __name__)

#form for logging in
class LoginForm(FlaskForm):
    username = StringField('Username', validators=[InputRequired(), Length(max=20)])
    password = PasswordField('Password', validators=[InputRequired(), Length(max=30)])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

#form for registering for an account
class RegisterForm(FlaskForm):
    email = StringField('Email', validators=[InputRequired(), Email(message='Invalid Email'), Length(max=40)])
    username = StringField('Username', validators=[InputRequired(), Length(max=20)])
    password = PasswordField('Password', validators=[InputRequired(), Length(max=30)])
    fname = StringField('First Name', validators=[InputRequired(), Length(max=20)])
    lname = StringField('Last Name', validators=[InputRequired(), Length(max=25)])
    submit = SubmitField('Register')

#form for resetting password
class PasswordResetForm(FlaskForm):
    email = StringField('Email', validators=[InputRequired()])
    old_password = PasswordField('Old Password', validators=[InputRequired()])
    new_password = PasswordField('New Password', validators=[InputRequired()])
    submit = SubmitField('Reset')

# @login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

#login route
@blueprint.route('/login', methods = ['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username = form.username.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('home.dashboard'))


    return render_template('auth/login.html', form = form)

#Register route
@blueprint.route('/register', methods = ['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='sha256')
        new_user = User(username = form.username.data, email = form.email.data, password = hashed_password, fname = form.fname.data, lname = form.lname.data, userType="User", incident_created=None, incident_assigned=None)

        db.session.add(new_user)
        db.session.commit()

    return render_template('auth/register.html', form=form)

#Password reset route
@blueprint.route('/reset-password', methods = ['GET', 'POST'])
def reset_password():
    form = PasswordResetForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user:
            if check_password_hash(user.password, form.old_password.data):
                new_pass_hashed = generate_password_hash(form.new_password.data, method='sha256')
                user.password = new_pass_hashed
                db.session.commit()

                flash('Password sucessfully reset.')
                return redirect(url_for('login'))

    return render_template('auth/reset_password.html', form=form)

#logout route
@blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

app/views/home.py
from flask import Blueprint, render_template, request
from flask_login import login_required
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField
from app.models import Incident, User, Incident_History
from app.views.forms import tagNames
# import db here once it is made

# creating blueprint
blueprint = Blueprint("home", __name__)

class SearchIncident(FlaskForm):
    tagSearch = SelectField('Search for tags:', choices = [])
    pocSearch = SelectField('Search for point of contact:', choices = [])
    search = SubmitField('Search')

# dashboard route
@blueprint.route('/dashboard', methods = ['GET', 'POST'])
@login_required
def dashboard():
    #queries db for all incidents and filters by incidentID
    Incidents = Incident.query.order_by(Incident.state.desc(), Incident.incidentID).all()
    contactNames = []

    for incident in Incidents:
        poc = incident.point_of_contact
        user = User.query.get(poc)
        point_of_contact = user.fname + " " + user.lname
        contactNames.append(point_of_contact)

    incidentZip = zip(Incidents, contactNames)

    form = SearchIncident()
    form.tagSearch.choices = [(tag, tag) for tag in tagNames]
    form.pocSearch.choices = [(user.id, str(user.fname + " " + user.lname)) for user in User.query.all()]

    if request.method == "POST":
        return search_incident(form)

    return render_template('home/dashboard.html', incidents = incidentZip, form = form)

# individual ticket route
@login_required
@blueprint.route('/ticket/<int:ticketID>')
def ticket(ticketID):
    #queries database for all incident history based on ticketID
    incident_history = Incident_History.query.filter_by(incident_id = ticketID).all()
    incident = Incident.query.get(ticketID)
    poc = User.query.get(incident.point_of_contact)
    assignee = User.query.get(incident.assignee)

    return render_template('home/ticket.html', history = incident_history, incident = incident, poc = poc, assignee = assignee)

# search for tags or point of contact
@login_required
@blueprint.route('/dashboard/search-results')
def search_incident(form):

    searchForm = SearchIncident()
    searchForm.tagSearch.choices = [(tag, tag) for tag in tagNames]
    searchForm.pocSearch.choices = [(user.id, str(user.fname + " " + user.lname)) for user in User.query.all()]

    if form.tagSearch.data != '':
        incidents = Incident.query.filter(Incident.tag.contains(form.tagSearch.data)).all()
    elif form.pocSearch.data != '':
        incidents = Incident.query.filter(Incident.point_of_contact == form.pocSearch.data).all()

    contactNames = []
    for incident in incidents:
        poc = incident.point_of_contact
        user = User.query.get(poc)
        point_of_contact = user.fname + " " + user.lname
        contactNames.append(point_of_contact)

    incidentZip = zip(incidents, contactNames)
    return render_template('home/dashboard.html', incidents = incidentZip, form = searchForm)

app/templates/home/dashboard.html
{% extends 'base.html' %}
{% block head %}
    {{ super() }}
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}<title>Dashboard</title> {% endblock title %}

{% endblock head %}

{% block body %}

<div class="limiter">
    <div class="container-login100">
                <div style="position:fixed; top:50px;">
                    <a href="{{url_for('forms.create_incident')}}">
                    <button class="login100-form-btn" action="{{url_for('forms.create_incident')}}">
                        Create Ticket
                    </button>
                    </a>
                    <a href="{{url_for('home.dashboard')}}">
                    <button class="login100-form-btn p-t-20" action="{{url_for('home.dashboard')}}">
                        Reset
                    </button>
                    </a>
                 </div>
                
               <div style="position:fixed; top:50px; left:50px;">
                    <a href="{{url_for('auth.logout')}}">
                    <button class="login100-form-btn" action="{{url_for('auth.logout')}}">
                        Log Out
                    </button>
                    </a>
               </div>

                <form style="position: fixed; top:10px; right:50px; width:300px; height:50px;" class="login100-form validate-form" action="{{url_for('home.dashboard')}}" method="POST">
                    <span class="login100-form-title p-b-10" style="font-size:20px;">
                        Search:
                    </span>
                {{ form.hidden_tag() }}
                <div class="wrap-input100 validate-input" style="height:50px;">
                    {{form.tagSearch(class="input100")}}
                    {{form.pocSearch(class="input100")}}
                    {{form.search(class="login100-form-btn")}}
                </div>
                </form>
                <div class="wrap-table100">
                  <div class="table100">
                    <table>
                        <thead>
                        <tr class="table100-head">
                            <th class="column1">Ticket No.</th>
                            <th class="column2">Title</th>
                            <th class="column3">Category</th>
                            <th class="column4">Reported By</th>
                            <th class="column5">State</th>
                            <th class="column6">Date Created</th>
                            <th class="column6">Date Resolved</th>
                            <th class="column6">View Ticket</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for incident in incidents %}
                        <tr>
                          <td class="column1">{{incident[0].incidentID}}</th>
                          <th class="column2">{{incident[0].title}}</th>
                          <th class="column3">{{incident[0].category}}</th>
                          <th class="column4">{{incident[1]}}</th>
                          <th class="column5">{{incident[0].state}}</th>
                          <th class="column6">{{incident[0].date_created}}</th>
                          <th class="column6">{{incident[0].date_resolved}}</th>
                          <th class="column6"><a href="{{url_for('home.ticket', ticketID = incident[0].incidentID)}}">View</a></th>
                        {% endfor %}
                        </tr>
                      </tbody>
                    </table>
            </div>
        </div>
    </div>
</div>


{% endblock %}
<!-- theme is from colorlib.com/wp/template/responsive-table-v1/--> 

app/templates/home/ticket.html
{% extends 'base.html' %}
{% block head %}
  {{ super() }}
  {% block title %}<title>Ticket </title>{% endblock title %}

{% endblock head %}

{% block body %}
{{ super () }}
 <div class="limiter">
   <div class="container-login100">
     <div style="position:fixed; top:50px; left:50px;">
          <a href="{{url_for('auth.logout')}}">
          <button class="login100-form-btn" action="{{url_for('auth.logout')}}">
              Log Out
          </button>
          </a>
     </div>
    <div style="position:fixed; top:50px;">
          <a href="{{url_for('home.dashboard')}}">
          <button class="login100-form-btn" action="{{url_for('home.dashboard')}}">
              Back to Dashboard
          </button>
          </a>
     </div>

     <div class="wrap-table100">
       <div class="table100">
         <table style="width: 700px; margin:50px auto 50px auto;">
           <tbody>
             <tr>
               <td colspan="2" style"word-wrap: break-word; border:0px; padding:9px; color:#fff; background: #36304a;">
                 <h1 style="margin-bottom:0px;">Incident Tracker</h1>
                 <p style="color: #ccc; margin-top:0px; margin-bottom:0px; font-style:italic;">
                   Our ticket management system for tracking IT issues.
                   </p>
                 </td>
               </tr>

               <tr style="padding: 10px;">
                 <td style="width: 400px; padding: 15px 0px 25px 25px; vertical-align: top;">
                   {% for update in history %}
                   <p style="font-style: italic; margin-bottom: 10px;">Ticket {{update.incident_id}} had the following update:</p>
                   <p style="margin-bottom: 10 px;">{{update.incident_history}}</p>
                   {% endfor %}

                   <table style="table-layout: fixed; width: 394px; border: 1px #e6e6e6; font-size: 11px;">
                     <tr>
                       <td word-wrap: break-word;>
                         <div style="margin: 9px;">
                           <h2 style="margin-bottom: 5px; margin-top: 10px; font-size: 12px;">Ticket {{incident.incidentID}}</h2>
                           <p style="margin-bottom: 10px;"><strong>Title:</strong> {{incident.title}}</p>
                           <p style="margin-bottom: 10px;"><strong>Summary:</strong> {{incident.description}}</p>
                           </div>
                         </td>
                       </tr>
                     </table>
                     <br />
                     <br />
                 </td>

                 <td style="width: 240px; vertical-align: top; padding: 10px 18px 10px 6px">
                   <div style="margin:15px 8px 0px 10px;padding: 9px; border: 1px #ccc solid; font-size: 10px;">
                     <strong>Ticket #</strong>{{incident.incidentID}} <a href="{{url_for('forms.edit_incident', ticketID = incident.incidentID)}}">Edit Ticket</a> <a href="{{url_for('forms.update_incident', ticketID = incident.incidentID)}}">Update Ticket</a>
                     <hr style="height: 1px; color: #ccc;" />
                     <strong>Date Created:</strong> {{incident.date_created}}<br />
                     <strong>Current State:</strong> {{incident.state}} <br />
                     <strong>Category (Priority):</strong> {{incident.category}}<br />
                     <strong>Tags:</strong> {{incident.tag}} <br />
                       <br />
                     <strong>Created By (Point of Contact):</strong><br /> {{poc.fname}} {{poc.lname}}<br />{{poc.email}} <br />
                     <strong>Current Assignee:</strong> {{assignee.fname}} {{assignee.lname}}<br />{{assignee.email}}

                     </div>
                   </td>

                 </tr>
             </tbody>
           </table>
         </div>
     </div>

   </div>
  </div>
{% endblock %}